# Generated by Django 5.2.8 on 2025-12-17 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cost_type'),
        ('groups', '0001_initial'),
        ('people', '0003_person_profile_photo_and_address_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='liability_release_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='liability_release_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='liability_release_name',
            field=models.CharField(blank=True, help_text='Name captured when the liability release was accepted.', max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='liability_release_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='media_release_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='media_release_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='media_release_name',
            field=models.CharField(blank=True, help_text='Name captured when the media release was accepted.', max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='media_release_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='EventRegistrationAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('is_minor', models.BooleanField(default=False, help_text='Captured at registration time to know if guardian details are required.')),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=255)),
                ('parent_guardian_email', models.EmailField(blank=True, max_length=254)),
                ('parent_guardian_phone', models.CharField(blank=True, max_length=50)),
                ('allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_attendees', to='events.event')),
                ('group', models.ForeignKey(blank=True, help_text='Optional group used for rosters and reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attendees', to='groups.group')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to='people.person')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.eventregistration')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
