# Generated by Django 5.2.8 on 2025-12-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_address_line1_and_more'),
        ('people', '0003_person_profile_photo_and_address_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationattendee',
            name='match_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventregistrationattendee',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('matched', 'Matched'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='eventregistrationattendee',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistrationattendee',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_event_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventregistrationattendee',
            name='suggested_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_event_registrations', to='people.person'),
        ),
    ]
