# Generated by Django 5.2.8 on 2025-12-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistrationattendee_match_notes_and_more'),
        ('groups', '0002_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_group',
            field=models.ForeignKey(blank=True, help_text='Auto-generated group that holds attendees for rosters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.group'),
        ),
    ]
