# Generated by Django 5.2.8 on 2025-12-22 03:22

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_registration_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('liability', 'Liability'), ('media', 'Media'), ('other', 'Other')], default='liability', max_length=20)),
                ('file', models.FileField(upload_to='events/releases/library/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='liability_release_custom',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_release_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='media_release_custom',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_release_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='liability_release_document',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'liability'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability_events', to='events.releasedocument'),
        ),
        migrations.AddField(
            model_name='event',
            name='media_release_document',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'media'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_events', to='events.releasedocument'),
        ),
    ]
