# Generated by Django 5.2.8 on 2026-10-01 19:08

import core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_releasedocument_event_liability_release_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='liability_release_custom',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_release_upload_path, validators=[core.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='event',
            name='media_release_custom',
            field=models.FileField(blank=True, null=True, upload_to=events.models.event_release_upload_path, validators=[core.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to='events/photos/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='releasedocument',
            name='file',
            field=models.FileField(upload_to='events/releases/library/', validators=[core.validators.validate_pdf]),
        ),
    ]
