# Generated by Django 5.2.17 on 2026-10-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_upload_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_attendee_details',
            field=models.BooleanField(default=False, help_text="Turn on for kids' events: each child must be registered with a birthdate and grade.", verbose_name='Require birthdate and grade for each attendee'),
        ),
    ]
