# Generated by Django 5.2.8 on 2025-12-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='Optional code used for kiosks or attendance sheets.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('volunteer', 'Volunteer Team'), ('checkin', 'Check-In Classroom'), ('community', 'Community Group'), ('event', 'Event Registration'), ('other', 'Other')], default='volunteer', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('meeting_schedule', models.CharField(blank=True, help_text='e.g. Sundays at 9:00am or Every 2nd Tuesday evening.', max_length=120)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
