"""
Print Service

Orchestrates label generation and sending to a configured thermal printer.
Label images are generated by LabelGenerator; adapters send them to the hardware.

Printer failure never blocks check-in completion — all errors are caught and logged.
"""

import logging

from ..models import PrinterConfiguration
from .printers import BrotherQLAdapter, ESCPOSAdapter

logger = logging.getLogger(__name__)


def get_printer_adapter(config: PrinterConfiguration):
    """Return the correct adapter instance for a PrinterConfiguration."""
    if config.printer_type == "brother_ql":
        if config.host:
            if config.port:
                identifier = f"tcp://{config.host}:{config.port}"
            else:
                identifier = f"tcp://{config.host}"
        else:
            identifier = ""
        return BrotherQLAdapter(identifier, config.ql_model or "QL-800")
    elif config.printer_type == "escpos":
        connection = f"tcp://{config.host}:{config.port or 9100}" if config.host else ""
        return ESCPOSAdapter(connection)
    else:
        raise ValueError(f"Unknown printer type: {config.printer_type!r}")


class PrintService:
    """Connects to a configured thermal printer for label printing and health checks."""

    def __init__(self, printer_config: PrinterConfiguration = None):
        if printer_config is None:
            printer_config = (
                PrinterConfiguration.objects.filter(is_active=True, is_default=True).first()
                or PrinterConfiguration.objects.filter(is_active=True).first()
            )
        self.printer_config = printer_config
        self._adapter = None

    @property
    def adapter(self):
        if self._adapter is None and self.printer_config:
            try:
                self._adapter = get_printer_adapter(self.printer_config)
            except Exception:
                logger.exception("Failed to initialise printer adapter")
        return self._adapter

    def print_checkins(self, checkins, session) -> bool:
        """
        Generate and print labels for a completed check-in group.
        Returns True on success, False on any error.
        Never raises — printer failures must not interrupt check-in flow.
        """
        if not self.printer_config or not self.adapter:
            return False
        checkins = list(checkins)
        if not checkins:
            return False
        try:
            from .label_generator import LabelGenerator
            images = LabelGenerator.build_label_set(checkins, session)
            return self.adapter.print_images(images)
        except Exception:
            logger.exception("Label print failed for check-in group")
            return False

    def test_printer(self) -> bool:
        """Send a test label to verify printer connectivity."""
        if not self.adapter:
            logger.error("No printer configured")
            return False
        return self.adapter.test_print()

    def is_printer_available(self) -> bool:
        """Return True if the configured printer is reachable."""
        if not self.adapter:
            return False
        return self.adapter.is_available()
