# Generated by Django 5.2.8 on 2026-05-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_migrate_config_simplify_room'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS attendance_attendancerecord CASCADE;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS attendance_checkinwindow CASCADE;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS attendance_checkinconfiguration_groups CASCADE;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS attendance_checkinconfiguration CASCADE;",
            migrations.RunSQL.noop,
        ),
    ]
