# Generated by Django 5.2.8 on 2026-05-01 11:18

from django.db import migrations


def drop_attendance_tables(apps, schema_editor):
    """Drop old attendance tables if they exist (works on both PG and SQLite)."""
    connection = schema_editor.connection
    tables = connection.introspection.table_names()
    old_tables = [
        "attendance_attendancerecord",
        "attendance_checkinwindow",
        "attendance_checkinconfiguration_groups",
        "attendance_checkinconfiguration",
    ]
    for table in old_tables:
        if table in tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {table};")


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_migrate_config_simplify_room'),
    ]

    operations = [
        migrations.RunPython(drop_attendance_tables, migrations.RunPython.noop),
    ]
