# Generated by Django 5.2.8 on 2026-05-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_remove_attendance_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerconfiguration',
            name='ql_model',
            field=models.CharField(blank=True, choices=[('QL-700', 'QL-700'), ('QL-800', 'QL-800'), ('QL-810W', 'QL-810W'), ('QL-820NWB', 'QL-820NWB'), ('QL-1100', 'QL-1100'), ('QL-1110NWB', 'QL-1110NWB')], default='QL-800', max_length=20),
        ),
        migrations.AlterField(
            model_name='printerconfiguration',
            name='printer_type',
            field=models.CharField(blank=True, choices=[('brother_ql', 'Brother QL'), ('escpos', 'ESC/POS Thermal')], max_length=50),
        ),
    ]
