# Generated by Django 5.2.8 on 2026-06-03 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_printerconfiguration_last_successful_print_at'),
        ('events', '0006_releasedocument_event_liability_release_custom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkinsession',
            constraint=models.UniqueConstraint(fields=('configuration', 'window', 'date'), name='uniq_session_per_config_window_date'),
        ),
    ]
