# Generated by Django 5.2.8 on 2026-06-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_printagent_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='printagent',
            name='label_width_mm',
            field=models.PositiveSmallIntegerField(default=62),
        ),
    ]
