# Generated by Django 5.2.8 on 2026-06-17 14:55

from django.db import migrations, models
from django.db.models import F


def backfill_arrived_at(apps, schema_editor):
    """Existing check-ins predate pre-staging — they were all 'arrived' the
    moment they were created, so backfill arrived_at = checked_in_at. Without
    this they'd read as 'expected/not arrived' and vanish from present counts."""
    CheckIn = apps.get_model("checkin", "CheckIn")
    CheckIn.objects.filter(arrived_at__isnull=True).update(arrived_at=F("checked_in_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_printagent_label_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_arrived_at, migrations.RunPython.noop),
    ]
