# Generated by Django 5.2.8 on 2026-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_checkin_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='printagent',
            name='label_rotation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None (wide label, e.g. 76mm Zebra)'), (90, '90° — fit a narrow roll (e.g. 62mm Brother)'), (270, '270° — narrow roll, other way up'), (180, '180° — upside down')], default=0),
        ),
    ]
