# Generated by Django 5.2.8 on 2026-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_printagent_label_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='print_emergency_phone',
            field=models.BooleanField(default=False),
        ),
    ]
