# Generated by Django 5.2.8 on 2026-06-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_room_max_age_room_max_grade_room_min_age_and_more'),
        ('groups', '0002_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinconfiguration',
            name='auto_enroll_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoenroll_configurations', to='groups.group'),
        ),
    ]
