# Generated by Django 5.2.8 on 2026-06-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0012_checkinconfiguration_auto_enroll_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='no_show',
            field=models.BooleanField(default=False),
        ),
    ]
