# Generated by Django 5.2.8 on 2026-06-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0013_checkin_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='printagent',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='printagent',
            name='local_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
