# Generated by Django 5.2.8 on 2026-06-25 21:09

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def resolve_active_duplicates(apps, schema_editor):
    """Make the data satisfy the new constraint before it's added: for any
    (session, person) with more than one active (not-checked-out) check-in, keep
    one and retire the rest. Keeps an arrived row over a pre-staged one; a
    redundant never-arrived duplicate is deleted, a duplicate arrival is checked
    out. No-op when there are no duplicates (the production case)."""
    CheckIn = apps.get_model("checkin", "CheckIn")
    groups = (
        CheckIn.objects.filter(checked_out_at__isnull=True)
        .values("session_id", "person_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for g in groups:
        rows = list(
            CheckIn.objects.filter(
                session_id=g["session_id"],
                person_id=g["person_id"],
                checked_out_at__isnull=True,
            ).order_by("arrived_at", "id")  # arrived (non-null) first; keep rows[0]
        )
        for extra in rows[1:]:
            if extra.arrived_at is None:
                extra.delete()  # redundant pre-staged duplicate that never arrived
            else:
                extra.checked_out_at = extra.arrived_at  # retire a duplicate arrival
                extra.save(update_fields=["checked_out_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0014_printagent_hostname_printagent_local_ip'),
        ('people', '0013_alter_person_phone_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(resolve_active_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='checkin',
            constraint=models.UniqueConstraint(condition=models.Q(('checked_out_at__isnull', True)), fields=('session', 'person'), name='uniq_active_checkin_per_person_session'),
        ),
    ]
