# Generated by Django 5.2.8 on 2026-06-25 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0015_checkin_uniq_active_checkin_per_person_session'),
        ('people', '0013_alter_person_phone_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['session', 'arrived_at', 'checked_out_at'], name='ck_checkin_session_state_idx'),
        ),
        migrations.AddIndex(
            model_name='checkin',
            index=models.Index(fields=['session', 'checked_out_at'], name='ck_checkin_session_out_idx'),
        ),
    ]
