# Generated by Django 5.2.8 on 2026-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0016_checkin_ck_checkin_session_state_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinconfiguration',
            name='checkout_enabled',
            field=models.BooleanField(default=False, help_text='Show the volunteer checkout screen (verify pickup codes) for this check-in.'),
        ),
    ]
