# Generated by Django 5.2.8 on 2026-01-04 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional context shown to staff when picking a check-in flow.')),
                ('welcome_message', models.CharField(blank=True, help_text='Copy displayed on the kiosk welcome screen.', max_length=255)),
                ('location_name', models.CharField(blank=True, help_text='Used on rosters and signage to differentiate kiosks.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive configurations stay hidden from the kiosk launcher.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Limit eligible classrooms/teams for this check-in flow.', related_name='checkin_configurations', to='groups.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, help_text='Optional reminder such as special instructions or locations.', max_length=120)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='attendance.checkinconfiguration')),
            ],
            options={
                'verbose_name': 'Check-In Window',
                'verbose_name_plural': 'Check-In Windows',
                'ordering': ['day_of_week', 'opens_at'],
            },
        ),
    ]
