# Generated by Django 5.2.8 on 2026-01-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkinwindow',
            options={'ordering': ['schedule_type', 'specific_date', 'day_of_week', 'opens_at'], 'verbose_name': 'Check-In Window', 'verbose_name_plural': 'Check-In Windows'},
        ),
        migrations.AddField(
            model_name='checkinwindow',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Recurring (weekly)'), ('specific_date', 'Specific date')], default='weekly', help_text='Choose weekly recurrence or select a specific date.', max_length=20),
        ),
        migrations.AddField(
            model_name='checkinwindow',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkinwindow',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], null=True),
        ),
    ]
