# Generated by Django 5.2.8 on 2026-01-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_checkinwindow_options_and_more'),
        ('events', '0006_releasedocument_event_liability_release_custom_and_more'),
        ('groups', '0002_groupmembership'),
        ('households', '0001_initial'),
        ('people', '0003_person_profile_photo_and_address_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('kiosk', 'Kiosk'), ('manual', 'Manual')], default='kiosk', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checkin_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='attendance.checkinwindow')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.checkinconfiguration')),
                ('event_occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='events.eventoccurrence')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='groups.group')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='households.household')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.person')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
