services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app/anchorpoint
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: anchorpoint
      POSTGRES_PASSWORD: anchorpoint
      POSTGRES_DB: anchorpoint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
