# Generated by Django 5.2.8 on 2026-06-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
