# Generated by Django 5.2.8 on 2026-10-01 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_releasedocument_event_liability_release_custom_and_more'),
        ('households', '0002_household_external_id'),
        ('people', '0013_alter_person_phone_opt_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyConflictFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_membership', models.BooleanField(default=False)),
                ('existing_households', models.CharField(blank=True, help_text="The child's families before the link (names, for review).", max_length=500)),
                ('filled_fields', models.JSONField(blank=True, default=dict, help_text='Blank fields this registration filled: {field: value}.')),
                ('status', models.CharField(choices=[('open', 'Needs review'), ('reviewed', 'Reviewed — OK'), ('undone', 'Undone')], default='open', max_length=20)),
                ('last_kiosk_alert_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_conflict_flags', to='people.person')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.person')),
                ('household', models.ForeignKey(blank=True, help_text='The family the child was linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_flags', to='households.household')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_conflict_flags', to='events.eventregistration')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'child'], name='households__status_915762_idx')],
            },
        ),
    ]
