# Generated by Django 5.2.8 on 2026-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='custody_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='custody_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='unauthorized_pickup',
            field=models.TextField(blank=True),
        ),
    ]
