# Generated by Django 5.2.8 on 2026-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_index_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('guest', 'Guest'), ('visitor', 'Visitor'), ('regular_attendee', 'Regular Attendee'), ('member', 'Member'), ('volunteer', 'Volunteer'), ('inactive', 'Inactive')], default='guest', max_length=50),
        ),
    ]
