# Generated by Django 5.2.8 on 2026-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_consent',
            field=models.BooleanField(default=False, help_text="Guardian permits photos / use of this person's image (relevant for minors)."),
        ),
    ]
