# Generated by Django 5.2.8 on 2026-06-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_person_photo_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
