# Generated by Django 5.2.8 on 2026-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_photo_consent_3state'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, default='', help_text='How this contact relates to the person (e.g. Grandmother, Family friend).', max_length=80),
        ),
    ]
