# Generated by Django 5.2.8 on 2026-06-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_person_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_opt_in',
            field=models.BooleanField(default=False, help_text='Can this person receive text messages at their phone number? Opt-in by default OFF — must be explicitly granted.'),
        ),
    ]
