# Generated by Django 5.2.8 on 2026-10-01 19:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_person_phone_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.validators.person_photo_upload_path, validators=[core.validators.validate_image_size]),
        ),
    ]
