"""
Django settings for anchorpoint project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Django forces DEBUG=False during test runs, which would otherwise activate the
# production HTTPS hardening below (secure cookies, SSL redirect) and break the
# HTTP test client. Detect test runs so that block stays production-only.
TESTING = "test" in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, ".env"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is required. "
        """Generate one with: python -c \"from django.core.management.utils 
        import get_random_secret_key; print(get_random_secret_key())\""""
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Google SSO
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")

# Allowed hosts - parse from environment variable
_allowed_hosts = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]

# CSRF trusted origins for Cloudflare tunnel
_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# Public base URL (e.g. https://anchorpoint.example.org) used by headless jobs
# such as the scheduled-communications worker to build absolute audio and
# Twilio status-callback URLs. Falls back to Organization Settings > Website
# and CSRF_TRUSTED_ORIGINS when unset (see messaging.services.get_site_base_url).
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "people",
    "households",
    "events",
    "groups",
    "messaging",
    "checkin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "anchorpoint.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.organization_settings",
            ],
        },
    },
]


WSGI_APPLICATION = "anchorpoint.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "anchorpoint"),
        "USER": os.getenv("DB_USER", "anchorpoint"),
        "PASSWORD": os.getenv("DB_PASS", "anchorpoint"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# During tests, isolate uploads in a throwaway directory so they don't collide
# with previously-uploaded files (which would make Django append a random
# suffix to the stored filename and break filename assertions) or pollute the
# real media dir.
if TESTING:
    import tempfile
    MEDIA_ROOT = tempfile.mkdtemp(prefix="anchorpoint-test-media-")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email configuration (Google Workspace SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
# Cap SMTP connection/operation time so a blocked or slow mail server (e.g.
# hosts that filter outbound SMTP) can never hang a request — sends fail fast
# and are caught instead of blocking user creation, registrations, etc.
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))


# Security settings for production (when not in DEBUG mode)
if not DEBUG and not TESTING:
    # HTTPS settings (Cloudflare terminates TLS and forwards X-Forwarded-Proto)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Default to enforcing HTTPS in production. Set REQUIRE_HTTPS=False only for
    # a deliberate non-TLS local prod test (otherwise cookies would leak over
    # plain HTTP). Previously this defaulted off, leaving secure cookies unset.
    _require_https = os.getenv("REQUIRE_HTTPS", "True").lower() == "true"
    if _require_https:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_SSL_REDIRECT = True
        # The container healthcheck probes http://localhost:8000/health/ directly
        # (no X-Forwarded-Proto), so without this it would be 301'd to https on a
        # non-TLS port and fail. Exempt the health endpoint from the SSL redirect.
        SECURE_REDIRECT_EXEMPT = [r"^health/$"]
        # HSTS: tell browsers to use HTTPS for a year. Disable by setting
        # SECURE_HSTS_SECONDS=0 if you are still validating the TLS setup.
        SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True

    # Additional security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"


# Logging — send Django and application logs to stdout/stderr so gunicorn and
# Docker capture them. Without this, app loggers (printer/SMS/email failures,
# etc.) have no handler and their messages are silently dropped in production.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
