# Generated by Django 5.2.8 on 2025-12-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organizationsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='sms_blackout_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='sms_blackout_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='twilio_phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_communications',
            field=models.BooleanField(default=False, help_text='Allow this user to manage SMS and phone blast communications.'),
        ),
    ]
