# Generated by Django 5.2.8 on 2026-01-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizationsettings_sms_blackout_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='kiosk_pin',
            field=models.CharField(blank=True, help_text='Optional 4-6 digit code required to unlock kiosk mode.', max_length=10),
        ),
    ]
