# Generated by Django 5.2.8 on 2026-05-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organizationsettings_kiosk_pin'),
        ('people', '0007_index_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='people.person'),
        ),
    ]
