# Generated by Django 5.2.8 on 2026-10-01 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_unique_user_email_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='family_alert_recipients',
            field=models.ManyToManyField(blank=True, help_text='Staff alerted when a child already in one family is linked to another.', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
