# Generated by Django 5.2.8 on 2026-10-01 19:08

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_family_conflict_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/logo/', validators=[core.validators.validate_image_size]),
        ),
    ]
